CREATE DATABASE IF NOT EXISTS catalog;
CREATE DATABASE IF NOT EXISTS inventory;
CREATE DATABASE IF NOT EXISTS orders;

CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'app';
GRANT ALL PRIVILEGES ON catalog.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON inventory.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON orders.* TO 'app'@'%';
FLUSH PRIVILEGES;
