################################ SERVICE ACCOUNTS ################################

#================== Inventory ==================#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory
  namespace: {{ .Values.namespace }}

---
#================== Order ==================#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  namespace: {{ .Values.namespace }}
