################################ VALUES ################################

#=============== Project ================#
namespace: shopping-cart

aws:
  region: ap-southeast-1
  account: "701604998432"

externalSecrets:
  rdsSecretName: "lab-shopping-cart-rds-credentials"

#================== Catalog ==================#
catalog:
  replicas: 1
  revisionHistoryLimit: 2
  maxSurge: 1
  maxUnavailable: 0
  image: "701604998432.dkr.ecr.ap-southeast-1.amazonaws.com/lab-shopping-cart-catalog"
  tag: "09ce813340b7023a6f242d92e788098072ed03b0"
  port: 4000
  targetGroupArn: "arn:aws:elasticloadbalancing:ap-southeast-1:701604998432:targetgroup/lab-shopping-cart-catalog/2b4f37dca9701e1a"
  resources:
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"

#================== Inventory ==================#
inventory:
  replicas: 1
  revisionHistoryLimit: 2
  maxSurge: 1
  maxUnavailable: 0
  image: "701604998432.dkr.ecr.ap-southeast-1.amazonaws.com/lab-shopping-cart-inventory"
  tag: "15181008dd6722232ba2a5ed829ee21dfecfaa6f"
  port: 5000
  targetGroupArn: "arn:aws:elasticloadbalancing:ap-southeast-1:701604998432:targetgroup/lab-shopping-cart-inventory/8661dbc0b032cdd8"
  resources:
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"

#================== Order ==================#
order:
  replicas: 1
  revisionHistoryLimit: 2
  maxSurge: 1
  maxUnavailable: 0
  image: "701604998432.dkr.ecr.ap-southeast-1.amazonaws.com/lab-shopping-cart-order"
  tag: "0214a9213d4598bd7ba42d13975658be0676e2cc"
  port: 6000
  targetGroupArn: "arn:aws:elasticloadbalancing:ap-southeast-1:701604998432:targetgroup/lab-shopping-cart-order/284b6aced33586cd"
  resources:
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
