############################ SECRETS #############################

#============== Grafana credentials ===============#
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: {{ index .Values "kube-prometheus-stack" "grafana" "adminUser" | quote }}
        admin_password: {{ `"{{ .admin_password }}"` }}
  data:
    - secretKey: admin_password
      remoteRef:
        key: {{ .Values.externalSecrets.secretName | quote }}
        property: grafana_password

---
#============== Alertmanager Slack credentials ===============#
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack
    creationPolicy: Owner
  data:
    - secretKey: slack-api-url
      remoteRef:
        key: {{ .Values.externalSecrets.secretName | quote }}
        property: slack_webhook_url
